      <p>We are delighted to invite you to the world&#8217;s first Open Knowledge Festival: a <a href="http://okfestival.org/programme">full week</a> of participatory sessions, keynote lectures, workshops, hackathons and satellite events in Helsinki, organised by diverse communities from over 40 nations across the globe.</p>

      <h4>Open Knowledge In Action</h4>

      <p>The 2012 theme of OKFestival is <em>Open Knowledge in Action</em>, looking at the <em>value</em> that can be generated by opening up knowledge, the ecosystems of organisations that can benefit from such sharing, and the impacts that transparency can have in our societies. What kinds of new professions, ideas and community initiatives can emerge within our governments, markets, networks and neighbourhoods as a result of these engagements?</p>

      <p><em>Open knowledge</em> is a comprehensive concept that involves sharing knowledge in all its forms – from genes to geodata, from literature to programming code – so that it can be freely used, modified and shared by anyone. This idea, based on the <a href="http://opendefinition.org" target="_blank">Open Definition</a>, provides an opportunity for positive transformation within our information society, where old hierarchies are replaced by agile, diverse, networked and experimental progress and cooperation.</p>

      <p>In an era of global digital communications, significant benefits are gained in all sectors of the society by opening up knowledge, including science, culture, governance and economy.</p>

      <h4>An Experimental Event Rooted in Collaboration</h4>

      <p>The exploration of this theme will not only be visible in the festival’s content, but also in its implementation as the first global event of its kind. This year, OKFestival combines two popular annual events &#8211; the <em><a title="OGDCamp" href="http://okfestival.org/open-government-data-camp/" target="_blank">Open Government Data Camp</a></em> and the <em><a title="OKCon" href="http://okfestival.org/open-knowledge-conference" target="_blank">Open Knowledge Conference</a>. </em>This combination allows us to highlight a set of 13 diverse <a href="http://okfestival.org/core-programme/" target="_blank">Topic Streams</a> organised by global teams of Guest Programme Planners.</p>

      <p>The festival week is a bold experiment in international collaborative event organising, with topics from open democracy and government data to open and smart cities to open business and corporate data to open design and hardware to data journalism. The main organisers of the event are the Open Knowledge Foundation, Aalto Media Factory and the Finnish Institute in London. </p>

      <h4>A Strong Network of Cooperation</h4>

      <p>In addition to the Core Team and Guest Programme Planners, OKFestival 2012 is made possible by a series of <a href="http://okfestival.org/organising-team/">partners and co-organisers</a>, including an advisory board of international leaders who steer the programme planning, including Janet Haven from Open Society Foundations, Peter Troxler from the International FabLab Association and Andrew Stott from the UK Cabinet Office.  </p>

      <p>OKFestival’s partners are Forum Virium Helsinki, Helsingin Sanomat, IBM, Finnish Innovation Fund Sitra, YLE and Martela. Co-partners include Finland’s Ministry of Education and Culture, Finland’s Ministry of Justice, EIT ICT Labs, Aalto Service Factory, AVO Open Networks For Learning, Open Ministry, and Aalto Pro.</p>

      <p>With this collaborative and experimental format, we aim to highlight the diversity of open knowledge and data initiatives from around the world. We will bring together civil society representatives, programmers, data wranglers, designers, students, members of government, local communities and citizens for a week of building new things and sharing great ideas.</p>

            <div class="photos">
            <img class="photo1" src="img/photo-1.jpg" alt="photo"/>
            <img class="photo2" src="img/photo-2.jpg" alt="photo"/>
            <img class="photo3" src="img/photo-3.jpg" alt="photo"/>
      </div>
