<?php include 'header.php'; ?>
        <link rel="stylesheet" href="css/style.css">
<?php include 'header-2.php'; ?>

<?php include 'hero.php'; ?>

        <div class="main-page">
            <div class="main-content">
                <div class="post-text">
                    <h2>A Week of Events Organised by a Diverse Set of Communities Around the World.</h2>
                    <p>We are delighted to share the world’s first Open Knowledge Festival with you: a week of participatory sessions, keynote lectures, workshops, hackathons and satellite events in Helsinki, Finland from 17-22 Sept 2012 with over 1,000 physical participants and 12,000 virtual participants from across the globe. OKFestival combined annual events <a href="http://okfestival.org/open-government-data-camp" target="_blank">OGDCamp</a> and <a href="http://okfestival.org/open-knowledge-conference/" target="_blank">OKCon</a> to form the first festival of its kind, and was entirely sold out this year. Its 2012 theme was <em>Open Knowledge in Action</em>, looking at the <em>value</em> that can be generated by opening up knowledge, the ecosystems of organisations that can benefit from such sharing, and the impacts transparency can have in our societies. With a <a href="http://www.slideshare.net/ardent_coeur/ok-festival2012" target="_blank">bold and experimental programme</a> focused on participation, organised through collaborations amongst over 100 guest planners from around the world leading 13 key <a href="http://okfestival.org/programme/" target="_blank">Topic Streams</a> from Government Transparency to Open Hardware, we aimed to highlight the true diversity of today&#8217;s open knowledge and data initiatives. <a href="http://okfestival.org/streams" target="_blank">View the online videostreams today</a> to see how hundreds of change-makers and experts from private, public and community sectors and helped build an international open knowledge ecosystem with us in Helsinki.</p>
                    <?php include 'social.php'; ?>
                </div>
            </div>

            <aside class="main-aside">
                <div class="illustration"></div>
            </aside>
        </div><!-- main-page -->
 
 <?php include 'footer.php'; ?>