<?php include 'header.php'; ?>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,900|Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="css/design2.css">

    </head>
    <body class="landing">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- stuff for the mobile nav -->
        <div id="page-wrapper-wrapper"><div id="page-wrapper">

        <header class="main-header">
            <div class="header-inner">
                <div id="main-menu-toggle" class="mobile-nav">
                    <p>Menu</p>
                    <div class="navicon">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <div class="header-text">
                    <h1 class="site-name"><img src="img/logo2.png" alt="Open Knowledge Festival"/></h1>
                    <div class="conference-meta">
                        <p class="tagline">The Open Knowledge & Data Event of the Year</p>
                        <p class="location">Helsinki, Finland</p>
                        <p class="date">September 17-22, 2012</p>
                    </div>
                </div>
            </div><!-- header-inner -->
            <nav role="navigation" class="main-navigation">
                <div class="navigation-inner">
                    <span id="main-menu-close" class="button button--close">Close Menu</span>
                    <ul class="menu">
                        <li><a href="">Programme</a></li>
                        <li><a href="">Topics</a></li>
                        <li><a href="">Tickets</a></li>
                        <li><a href="">About</a></li>
                        <li><a href="">Info</a></li>
                        <li><a href="">Contact</a></li>
                    </ul>
                </div><!-- navigation-inner -->
            </nav>
        </header>

<?php include 'hero.php'; ?>


        <div class="main-page">
            <div class="main-content">
                    <div class="post-text">
                        <h2>A Week of Events Organised by a Diverse Set of Communities Around the World.</h2>
                        <p>We are delighted to share the world’s first Open Knowledge Festival with you: a week of participatory sessions, keynote lectures, workshops, hackathons and satellite events in Helsinki, Finland from 17-22 Sept 2012 with over 1,000 physical participants and 12,000 virtual participants from across the globe. OKFestival combined annual events <a href="http://okfestival.org/open-government-data-camp" target="_blank">OGDCamp</a> and <a href="http://okfestival.org/open-knowledge-conference/" target="_blank">OKCon</a> to form the first festival of its kind, and was entirely sold out this year. Its 2012 theme was <em>Open Knowledge in Action</em>, looking at the <em>value</em> that can be generated by opening up knowledge, the ecosystems of organisations that can benefit from such sharing, and the impacts transparency can have in our societies. With a <a href="http://www.slideshare.net/ardent_coeur/ok-festival2012" target="_blank">bold and experimental programme</a> focused on participation, organised through collaborations amongst over 100 guest planners from around the world leading 13 key <a href="http://okfestival.org/programme/" target="_blank">Topic Streams</a> from Government Transparency to Open Hardware, we aimed to highlight the true diversity of today&#8217;s open knowledge and data initiatives. <a href="http://okfestival.org/streams" target="_blank">View the online videostreams today</a> to see how hundreds of change-makers and experts from private, public and community sectors and helped build an international open knowledge ecosystem with us in Helsinki.</p>
                        <?php include 'social.php'; ?>
                    </div>
            </div>
            <aside class="main-aside">
                <div class="illustration"><img src="img/logo2-black.png" alt="illustration"/></div>
            </aside>
        </div><!-- main-page -->
 
 <?php include 'footer.php'; ?>